name = "xfun"
uuid = "77570dc4-1096-48f5-86af-d733cda51951"
authors = ["szcf-weiya <szcfweiya@gmail.com>"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[targets]
test = ["Test"]